### ISSUE TITLE
Possible Runaway Gas Issue blocking Withdraw

### ISSUE THREAD

**Issue by naterush** [EtherDogs/PersonalBank#1]
Short Description: if there are more than 255 delegates, I think the loop that starts on line 82 will cause the transaction to run out of gas under some conditions, essentially locking all money in this contract. 

If there are more than 255 heirs, than the loop on line 82 (uint8 i = 0; i < heirs.length; i++) will cause the variable i to overflow and wrap around. This will cause this loop to run as long as there is gas left in the transaction (as i will always be < heirs.length). This will use all the remaining gas, and not let any money be taken from the contract. 

To see a contract with a similar issue, check out this post/contract here: https://www.reddit.com/r/ethereum/comments/4ghzhv/governmentals_1100_eth_jackpot_payout_is_stuck/

As far as I can tell, there are two possible quick fixes:
1. Make the int bigger than int8. I don't think this is a great solution because there is still the issue the owner could add enough delegates (and then die), that this loop will still cause a runaway gas attack (just due to the sheer amount of addition necessary). This might be prevented by the fact that adding someone also runs through the loops (and thus there would be a max automatically), but that seems like a bad thing to rely upon.

2. Change all arrays to mappings. Then, there are no loops, there is nothing to worry about. Also, now you don't have to have a concept of heirIndexs - just map an heir to their number of points. If heirPoints[heirAddress] > 0, then they exist. Also, to fix the loop in line 82 (as you cannot iterate through mappings), just have a variable that stores the total number of points, and is updated when an heir is added/deleted/modified. 

This would also have the added benefit of making it so there was a single function for adding/removing/modifying delegates - making things much more auditable. Also, you could use function modifiers to check if they exist to call functions.

**Comment by Rideron85** [comment]
Hi Nate, thanks for posting. You are right, there is no need for an array. 
I don't remember why I thought it was necessary to iterate but is clearly not the case here. 
Fixed in [435848c](https://github.com/EtherDogs/PersonalBank/commit/435848c595cb469dfe92f500e8fed3262d6cb010)
